app/add/forms.py
from multiprocessing import Condition
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField
from wtforms.validators import DataRequired

class AddForm(FlaskForm):
    name = StringField(label="Name", validators=[DataRequired()])
    type = StringField(label="Type", validators=[DataRequired()])
    item_discription = StringField(label="Discription", validators=[DataRequired()])
    condition = StringField(label="Condition", validators=[DataRequired()])
    serial = StringField(label="Serial Number", validators=[DataRequired()])
    date_manufactured = StringField(label="Date Manufactured", validators=[DataRequired()])
    cost = StringField(label="Cost", validators=[DataRequired()])
    purchase_date = StringField(label="Purchase Date", validators=[DataRequired()])
    submit = SubmitField(label="Save")

app/add/views.py
from re import A
from flask import Blueprint, flash,render_template
from flask_login import login_required
from ..models import Asset, db
from .forms import AddForm

add_bp = Blueprint("add_bp", __name__, template_folder="templates",
                    static_folder="static")


@add_bp.route("/", methods=["POST", "GET"])
@login_required
def add():
    add_form = AddForm()
    
    if add_form.validate_on_submit():
        asset = Asset(asset_tag=get_tag(), name=add_form.name.data, type=add_form.type.data,
                        item_discription=add_form.item_discription.data, condition=add_form.condition.data,
                        serial=add_form.serial.data, date_manufactured=add_form.date_manufactured.data,
                        cost=add_form.cost.data, purchase_date=add_form.purchase_date.data)
        
        db.session.add(asset)
        db.session.commit()

        flash("Asset added succesfully", category="success")
        
    return render_template("add/add.html", form=add_form)


def get_tag():
    import string
    import random

    all_chars = string.ascii_letters + string.digits
    # print(all_chars)

    chars_count = len(all_chars)
    # print(chars_count)

    serial_list = " "
    count = 10

    while count > 0:

        random_number = random.randint(0, chars_count - 1)

        random_character = all_chars[random_number]

        serial_list += random_character

        count -= 1  # count = count - 1

    return serial_list

app/add/templates/add/add.html
{% extends "base.html" %}

{% block head %}
{{super()}}

{% block styles %}
<link rel="stylesheet" href="{{url_for('add_bp.static', filename='add/styles.css')}}">
{% endblock %}
{% endblock %}

{% block title %}Add{% endblock %}

{% block content %}
<div class="">
    <section>
        <div>
            <h1> Create Asset</h1>
        </div>

        <div class="row">
            <div class="col-md-8 offset-md-2 form-div mb-3">

                <form action="{{ url_for('add_bp.add') }}" method="POST" novalidate class="add-form mb-3">
                    <div class="form-body">
                        {{ form.csrf_token }}
                        <div class="form-group row mb-3">
                            <div class="col-form-label col-sm-2">{{ form.name.label }}</div>
                            <div class="col-sm-6">
                                {{form.name(size=30, class="form-control")}}
                            </div>
                            <div class="invalid-feedback">
                                {% for error in form.name.errors %}
                                <span>{{ error }}</span>
                                {% endfor %}
                            </div>
                        </div>
                        <div class="form-group row mb-3">
                            <div class="col-form-label col-sm-2">{{ form.type.label }}</div>
                            <div class="col-sm-6">
                                {{form.type(size=30, class="form-control")}}
                            </div>

                            <div class="invalid-feedback">
                                {% for error in form.type.errors %}
                                <span>{{ error }}</span>
                                {% endfor %}
                            </div>
                        </div>
                        <div class="form-group row mb-3">
                            <div class="col-form-label col-sm-2">{{ form.item_discription.label }}</div>
                            <div class="col-sm-6">
                                {{form.item_discription(size=30, class="form-control")}}
                            </div>
                            
                            <div class="invalid-feedback">
                                {% for error in form.item_discription.errors %}
                                <span>{{ error }}</span>
                                {% endfor %}
                            </div>
                        </div>
                        <div class="form-group row mb-3">
                            <div class="col-form-label col-sm-2">{{ form.condition.label }}</div>
                            <div class="col-sm-6">
                                {{form.condition(size=30, class="form-control")}}
                            </div>
                            
                            <div class="invalid-feedback">
                                {% for error in form.condition.errors %}
                                <span>{{ error }}</span>
                                {% endfor %}
                            </div>
                        </div>
                        <div class="form-group row mb-3">
                            <div class="col-form-label col-sm-2">{{ form.serial.label }}</div>
                            <div class="col-sm-6">
                                {{form.serial(size=30, class="form-control")}}
                            </div>
                            
                            <div class="invalid-feedback">
                                {% for error in form.serial.errors %}
                                <span>{{ error }}</span>
                                {% endfor %}
                            </div>
                        </div>
                        <div class="form-group row ">
                            <div class="col-form-label col-sm-2">{{ form.date_manufactured.label }}</div>
                            <div class="col-sm-6">
                                {{form.date_manufactured(size=30, class="form-control")}}
                            </div>
                            
                            <div class="invalid-feedback">
                                {% for error in form.date_manufactured.errors %}
                                <span>{{ error }}</span>
                                {% endfor %}
                            </div>
                        </div>
                        <div class="form-group row mb-3">
                            <div class="col-form-label col-sm-2">{{ form.cost.label }}</div>
                            <div class="col-sm-6">
                                {{form.cost(size=30, class="form-control")}}
                            </div>
                            
                            <div class="invalid-feedback">
                                {% for error in form.cost.errors %}
                                <span>{{ error }}</span>
                                {% endfor %}
                            </div>
                        </div>
                        <div class="form-group row mb-3">
                            <div class="col-form-label col-sm-2">{{ form.purchase_date.label }}</div>
                            <div class="col-sm-6">
                                {{form.purchase_date(size=30, class="form-control")}}
                            </div>
                            
                            <div class="invalid-feedback">
                                {% for error in form.purchase_date.errors %}
                                <span>{{ error }}</span>
                                {% endfor %}
                            </div>
                        </div>

                        <div class="submit-button navbar">
                            
                            {{ form.submit(class="btn btn-primary ms-auto") }}
                        </div>
                    </div>

                </form>
                {% with messages = get_flashed_messages() %}
                {% if messages %}
                <ul class="flashes">
                    {% for message in messages %}
                    <li>{{ message }}</li>
                    {% endfor %}
                </ul>
                {% endif %}
                {% endwith %}
            </div>
        </div>
    </section>
</div>
{% endblock %}